# SLURM

paths :   
    out_folder: "/my_data/Results/LCC_Aer_SITS_FLAIR_HUB/results/"
    out_model_name: test-lib

    train_csv: /my_data/FLAIR_HUB/ALL_CSV/FLAIR_HUB_TRAIN.csv
    val_csv: /my_data/FLAIR_HUB/ALL_CSV/FLAIR_HUB_VALID.csv
    test_csv: /my_data/FLAIR_HUB/ALL_CSV/FLAIR_HUB_TEST.csv
    global_mtd_folder: /my_data/FLAIR_HUB/GLOBAL_ALL_MTD/
    ckpt_model_path: "/my_data/Results/LCC_Aer_SITS_FLAIR_HUB/results/test-lib/checkpoints/"

tasks: 

    train: True
    train_tasks: 
        init_weights_only_from_ckpt: False
        resume_training_from_ckpt: False

    predict: False
    write_files: True
    georeferencing_output: True
    metrics_only: False

hyperparams:

    num_epochs: 150
    batch_size: 10
    seed: 2025
    learning_rate: 0.00005

    optimizer: adamw  # [sgd / adam / adamw]
    optim_weight_decay: 0.01
    optim_betas: [0.9, 0.999]

    scheduler: one_cycle_lr #  [one_cycle_lr / reduce_on_plateau / cycle_then_plateau]
    warmup_fraction: 0.2 # if using one_cycle_lr. [0-1]
    plateau_patience: 10 # if using cycle_then_plateau

hardware:
    accelerator: 'gpu'
    num_nodes: 1
    gpus_per_node: 1
    strategy: 'auto' # ddp_find_unused_parameters_true if num_nodes > 1
    num_workers: 10

saving:   
    ckpt_save_also_last: True
    ckpt_weights_only: False
    ckpt_monitor: 'val_miou'
    ckpt_monitor_mode: 'max'
    ckpt_earlystopping_patience: 20
    cp_csv_and_conf_to_output: True
    enable_progress_bar: True
    progress_rate: 100
    ckpt_verbose: True
    verbose_config: False




